#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaDirectAcquisitionOfferDetailsWidget

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK::Params
{

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget
// 0x0058 (0x0058 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue;                 // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAccountItemDefinition*             CallFunc_GetFirstGrantItemDefinition_ReturnValue;  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDataTableRowHandle                    K2Node_MakeStruct_DataTableRowHandle;              // 0x0028(0x0010)(NoDestructor)
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate;              // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget) == 0x000058, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, EntryPoint) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, CallFunc_GetOfferInfo_ReturnValue) == 0x000010, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::CallFunc_GetOfferInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, CallFunc_GetFirstGrantItemDefinition_ReturnValue) == 0x000018, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::CallFunc_GetFirstGrantItemDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, K2Node_ComponentBoundEvent_Button) == 0x000020, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, K2Node_MakeStruct_DataTableRowHandle) == 0x000028, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::K2Node_MakeStruct_DataTableRowHandle' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000038, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, CallFunc_GetUINavigationManager_ReturnValue) == 0x000048, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget, CallFunc_MakeLiteralInt_ReturnValue) == 0x000050, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_ExecuteUbergraph_AthenaDirectAcquisitionOfferDetailsWidget::CallFunc_MakeLiteralInt_ReturnValue' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.UpdateFromOffer
// 0x0218 (0x0218 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicFontMaterial_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue2;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue2;          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAccountItemDefinition*             CallFunc_GetFirstGrantItemDefinition_ReturnValue;  // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaGliderItemDefinition*            K2Node_DynamicCast_AsAthena_Glider_Item_Definition; // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue2;                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue;                   // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetOfferId_ReturnValue;                   // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsOwned_ReturnValue;                      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue3;                // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetShortDescription_ReturnValue;          // 0x0088(0x0018)()
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDescription_ReturnValue;               // 0x00A8(0x0018)()
	class FText                                   CallFunc_GetName_ReturnValue;                      // 0x00C0(0x0018)()
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x00D8(0x0018)()
	int32                                         Temp_int_Variable2;                                // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue4;                // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAccountItemDefinition*             CallFunc_GetFirstGrantItemDefinition_ReturnValue2; // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue5;                // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue; // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasDisplayAsset_ReturnValue;              // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFortMtxDetailsAttribute>       CallFunc_GetDetailsAttributes_ReturnValue;         // 0x0120(0x0010)(ZeroConstructor, ReferenceParm)
	EFortRarity                                   CallFunc_GetRarity_ReturnValue;                    // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortMtxDetailsAttribute               CallFunc_Array_Get_Item;                           // 0x0138(0x0030)()
	struct FFortRarityItemData                    CallFunc_BPGetRarityData_ReturnValue;              // 0x0168(0x0080)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStoreMain_OfferDetailsAttribute_C*     CallFunc_Create_ReturnValue;                       // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20C[0x4];                                      // 0x020C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer) == 0x000218, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetDynamicFontMaterial_ReturnValue) == 0x000008, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetDynamicFontMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_MakeLiteralName_ReturnValue) == 0x000010, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_MakeLiteralName_ReturnValue2) == 0x000018, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_MakeLiteralName_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetDynamicMaterial_ReturnValue2) == 0x000020, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetDynamicMaterial_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferInfo_ReturnValue) == 0x000028, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetFirstGrantItemDefinition_ReturnValue) == 0x000030, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetFirstGrantItemDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, Temp_int_Array_Index_Variable) == 0x000038, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, K2Node_DynamicCast_AsAthena_Glider_Item_Definition) == 0x000040, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::K2Node_DynamicCast_AsAthena_Glider_Item_Definition' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_MakeLiteralInt_ReturnValue) == 0x00004C, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_MakeLiteralInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferInfo_ReturnValue2) == 0x000050, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferInfo_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetContext_ReturnValue) == 0x000058, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferId_ReturnValue) == 0x000060, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferId_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_IsOwned_ReturnValue) == 0x000070, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_IsOwned_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, Temp_int_Variable) == 0x000074, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferInfo_ReturnValue3) == 0x000078, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferInfo_ReturnValue3' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, Temp_int_Loop_Counter_Variable) == 0x000080, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetShortDescription_ReturnValue) == 0x000088, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetShortDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_Add_IntInt_ReturnValue) == 0x0000A0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetDescription_ReturnValue) == 0x0000A8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetName_ReturnValue) == 0x0000C0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_TextToUpper_ReturnValue) == 0x0000D8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, Temp_int_Variable2) == 0x0000F0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferInfo_ReturnValue4) == 0x0000F8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferInfo_ReturnValue4' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetFirstGrantItemDefinition_ReturnValue2) == 0x000100, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetFirstGrantItemDefinition_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOfferInfo_ReturnValue5) == 0x000108, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOfferInfo_ReturnValue5' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue) == 0x000110, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_HasDisplayAsset_ReturnValue) == 0x000118, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_HasDisplayAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetDetailsAttributes_ReturnValue) == 0x000120, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetDetailsAttributes_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetRarity_ReturnValue) == 0x000130, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetRarity_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_Array_Get_Item) == 0x000138, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_BPGetRarityData_ReturnValue) == 0x000168, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_BPGetRarityData_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_Array_Length_ReturnValue) == 0x0001E8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_Less_IntInt_ReturnValue) == 0x0001EC, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_GetOwningPlayer_ReturnValue) == 0x0001F0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, Temp_bool_Variable) == 0x0001F8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_Create_ReturnValue) == 0x000200, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, K2Node_Select_Default) == 0x000208, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000210, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_UpdateFromOffer::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.HandleBack
// 0x0001 (0x0001 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack final
{
public:
	bool                                          PassThrough;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack) == 0x000001, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack) == 0x000001, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack, PassThrough) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandleBack::PassThrough' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.PopDetails
// 0x0008 (0x0008 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails final
{
public:
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails) == 0x000008, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails, CallFunc_GetUIManagerWidget_ReturnValue) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_PopDetails::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.SetupPrice
// 0x01A8 (0x01A8 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice final
{
public:
	int32                                         PriceIndex;                                        // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UIconTextButton_C*                      PurchaseButton;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                PriceContainer;                                    // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             NormalPriceText;                                   // 0x0018(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                SalePriceContainer;                                // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             SalePriceText;                                     // 0x0028(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 CurrencyImage;                                     // 0x0030(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue;                 // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPriceInMTX_ReturnValue;                 // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetOfferId_ReturnValue;                   // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B[0x5];                                       // 0x005B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue2;                // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetSalePrice_SalePrice;                   // 0x0068(0x0018)()
	bool                                          CallFunc_GetSalePrice_ReturnValue;                 // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetNormalPrice_ReturnValue;               // 0x0088(0x0018)()
	ESlateVisibility                              K2Node_Select_Default;                             // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetPriceItem_RequiredItemCount;           // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAccountItemDefinition*             CallFunc_GetPriceItem_ReturnValue;                 // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_GetSmallPreviewImageBrush_ReturnValue;    // 0x00B0(0x0090)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue;                   // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable;                                // 0x0150(0x0018)()
	EOfferPurchaseError                           CallFunc_CanPurchaseOffer_ReturnValue;             // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue2;         // 0x016A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16B[0x5];                                      // 0x016B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable2;                               // 0x0170(0x0018)()
	bool                                          Temp_bool_Variable2;                               // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select2_Default;                            // 0x0190(0x0018)()
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice) == 0x0001A8, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, PriceIndex) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::PriceIndex' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, PurchaseButton) == 0x000008, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::PurchaseButton' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, PriceContainer) == 0x000010, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::PriceContainer' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, NormalPriceText) == 0x000018, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::NormalPriceText' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, SalePriceContainer) == 0x000020, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::SalePriceContainer' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, SalePriceText) == 0x000028, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::SalePriceText' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CurrencyImage) == 0x000030, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CurrencyImage' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetOfferInfo_ReturnValue) == 0x000038, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetOfferInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_IsPriceInMTX_ReturnValue) == 0x000040, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_IsPriceInMTX_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetOfferId_ReturnValue) == 0x000048, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetOfferId_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_byte_Variable) == 0x000058, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_byte_Variable2) == 0x000059, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_bool_Variable) == 0x00005A, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetOfferInfo_ReturnValue2) == 0x000060, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetOfferInfo_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetSalePrice_SalePrice) == 0x000068, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetSalePrice_SalePrice' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetSalePrice_ReturnValue) == 0x000080, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetSalePrice_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetNormalPrice_ReturnValue) == 0x000088, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetNormalPrice_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, K2Node_Select_Default) == 0x0000A0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetPriceItem_RequiredItemCount) == 0x0000A4, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetPriceItem_RequiredItemCount' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetPriceItem_ReturnValue) == 0x0000A8, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetPriceItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetSmallPreviewImageBrush_ReturnValue) == 0x0000B0, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetSmallPreviewImageBrush_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_IsValid_ReturnValue) == 0x000140, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_GetContext_ReturnValue) == 0x000148, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_text_Variable) == 0x000150, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_CanPurchaseOffer_ReturnValue) == 0x000168, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_CanPurchaseOffer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000169, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, CallFunc_EqualEqual_ByteByte_ReturnValue2) == 0x00016A, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::CallFunc_EqualEqual_ByteByte_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_text_Variable2) == 0x000170, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_text_Variable2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, Temp_bool_Variable2) == 0x000188, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice, K2Node_Select2_Default) == 0x000190, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_SetupPrice::K2Node_Select2_Default' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.HandlePurchaseOfferComplete
// 0x0028 (0x0028 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete final
{
public:
	bool                                          Success;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortUIManagerWidget_NUI*               CallFunc_GetUIManagerWidget_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaDirectAcquisitionOfferPurchasedWidget_C* CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete) == 0x000028, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete, Success) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete::Success' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete, CallFunc_GetOfferInfo_ReturnValue) == 0x000008, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete::CallFunc_GetOfferInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete, CallFunc_GetUIManagerWidget_ReturnValue) == 0x000010, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete::CallFunc_GetUIManagerWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete, CallFunc_GetOwningPlayer_ReturnValue) == 0x000018, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete, CallFunc_Create_ReturnValue) == 0x000020, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_HandlePurchaseOfferComplete::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function AthenaDirectAcquisitionOfferDetailsWidget.AthenaDirectAcquisitionOfferDetailsWidget_C.AttemptPurchase
// 0x0070 (0x0070 - 0x0000)
struct AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase final
{
public:
	int32                                         PriceIndex;                                        // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bSuccess)>                K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue;                   // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetOfferId_ReturnValue;                   // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue2;                  // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOfferPurchaseError                           CallFunc_CanPurchaseOffer_ReturnValue;             // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortDirectAcquisitionOfferInfo*        CallFunc_GetOfferInfo_ReturnValue2;                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetOfferId_ReturnValue2;                  // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EOfferPurchaseError                           CallFunc_PurchaseOffer_ReturnValue;                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase) == 0x000008, "Wrong alignment on AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase");
static_assert(sizeof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase) == 0x000070, "Wrong size on AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, PriceIndex) == 0x000000, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::PriceIndex' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetUINavigationManager_ReturnValue) == 0x000008, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetUINavigationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetContext_ReturnValue) == 0x000020, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetOfferInfo_ReturnValue) == 0x000028, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetOfferInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetOfferId_ReturnValue) == 0x000030, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetOfferId_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetContext_ReturnValue2) == 0x000040, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_CanPurchaseOffer_ReturnValue) == 0x000048, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_CanPurchaseOffer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000049, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetOfferInfo_ReturnValue2) == 0x000050, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetOfferInfo_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_GetOfferId_ReturnValue2) == 0x000058, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_GetOfferId_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase, CallFunc_PurchaseOffer_ReturnValue) == 0x000068, "Member 'AthenaDirectAcquisitionOfferDetailsWidget_C_AttemptPurchase::CallFunc_PurchaseOffer_ReturnValue' has a wrong offset!");

}

