#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TRV_Candle_02

#include "Basic.hpp"

#include "BP_TRV_Candle_02_classes.hpp"


namespace SDK
{

// Function BP_TRV_Candle_02.BP_TRV_Candle_02_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_TRV_Candle_02_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TRV_Candle_02_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

