#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CommonUI_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function CampaignMapWidget.CampaignMapWidget_C.ExecuteUbergraph_CampaignMapWidget
// 0x0080 (0x0080 - 0x0000)
struct CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button3;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bUsingGamepad)>           K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue2;        // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate2;             // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetNumWidgets_ReturnValue;                // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue3;        // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue4;        // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonUIContext*                       CallFunc_GetContext_ReturnValue2;                  // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button2;                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget) == 0x000008, "Wrong alignment on CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget");
static_assert(sizeof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget) == 0x000080, "Wrong size on CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, EntryPoint) == 0x000000, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000004, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_Subtract_IntInt_ReturnValue) == 0x000008, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, K2Node_ComponentBoundEvent_Button3) == 0x000010, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::K2Node_ComponentBoundEvent_Button3' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetActiveWidgetIndex_ReturnValue2) == 0x000028, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetActiveWidgetIndex_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, K2Node_CreateDelegate_OutputDelegate2) == 0x000030, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetNumWidgets_ReturnValue) == 0x000040, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetNumWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetActiveWidgetIndex_ReturnValue3) == 0x000044, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetActiveWidgetIndex_ReturnValue3' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_Add_IntInt_ReturnValue2) == 0x000048, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetActiveWidgetIndex_ReturnValue4) == 0x00004C, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetActiveWidgetIndex_ReturnValue4' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000050, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000051, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetContext_ReturnValue) == 0x000058, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetQuestManager_ReturnValue) == 0x000060, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, CallFunc_GetContext_ReturnValue2) == 0x000068, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, K2Node_ComponentBoundEvent_Button2) == 0x000070, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::K2Node_ComponentBoundEvent_Button2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget, K2Node_ComponentBoundEvent_Button) == 0x000078, "Member 'CampaignMapWidget_C_ExecuteUbergraph_CampaignMapWidget::K2Node_ComponentBoundEvent_Button' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'CampaignMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'CampaignMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'CampaignMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.Update
// 0x0180 (0x0180 - 0x0000)
struct CampaignMapWidget_C_Update final
{
public:
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0000(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData2;             // 0x0040(0x0040)(HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData3;             // 0x0090(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D0(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E0(0x0018)()
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData4;             // 0x0100(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array2;                           // 0x0140(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue2;                      // 0x0150(0x0018)()
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UProtoCampaignMapPage_C*                K2Node_DynamicCast_AsProto_Campaign_Map_Page;      // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CampaignMapWidget_C_Update) == 0x000008, "Wrong alignment on CampaignMapWidget_C_Update");
static_assert(sizeof(CampaignMapWidget_C_Update) == 0x000180, "Wrong size on CampaignMapWidget_C_Update");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeStruct_FormatArgumentData) == 0x000000, "Member 'CampaignMapWidget_C_Update::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeStruct_FormatArgumentData2) == 0x000040, "Member 'CampaignMapWidget_C_Update::K2Node_MakeStruct_FormatArgumentData2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_Add_IntInt_ReturnValue) == 0x000080, "Member 'CampaignMapWidget_C_Update::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_Add_IntInt_ReturnValue2) == 0x000084, "Member 'CampaignMapWidget_C_Update::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000088, "Member 'CampaignMapWidget_C_Update::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeStruct_FormatArgumentData3) == 0x000090, "Member 'CampaignMapWidget_C_Update::K2Node_MakeStruct_FormatArgumentData3' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeArray_Array) == 0x0000D0, "Member 'CampaignMapWidget_C_Update::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_Format_ReturnValue) == 0x0000E0, "Member 'CampaignMapWidget_C_Update::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_Subtract_IntInt_ReturnValue) == 0x0000F8, "Member 'CampaignMapWidget_C_Update::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeStruct_FormatArgumentData4) == 0x000100, "Member 'CampaignMapWidget_C_Update::K2Node_MakeStruct_FormatArgumentData4' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_MakeArray_Array2) == 0x000140, "Member 'CampaignMapWidget_C_Update::K2Node_MakeArray_Array2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_Format_ReturnValue2) == 0x000150, "Member 'CampaignMapWidget_C_Update::CallFunc_Format_ReturnValue2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, CallFunc_GetWidgetAtIndex_ReturnValue) == 0x000168, "Member 'CampaignMapWidget_C_Update::CallFunc_GetWidgetAtIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_DynamicCast_AsProto_Campaign_Map_Page) == 0x000170, "Member 'CampaignMapWidget_C_Update::K2Node_DynamicCast_AsProto_Campaign_Map_Page' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Update, K2Node_DynamicCast_bSuccess) == 0x000178, "Member 'CampaignMapWidget_C_Update::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.Find Active Page
// 0x0040 (0x0040 - 0x0000)
struct CampaignMapWidget_C_Find_Active_Page final
{
public:
	int32                                         Temp_int_Variable;                                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumWidgets_ReturnValue;                // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UProtoCampaignMapPage_C*                K2Node_DynamicCast_AsProto_Campaign_Map_Page;      // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckForMainQuest_TargetQuestFound;       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckForMainQuest_TargetQuestPageIndex;   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CampaignMapWidget_C_Find_Active_Page) == 0x000008, "Wrong alignment on CampaignMapWidget_C_Find_Active_Page");
static_assert(sizeof(CampaignMapWidget_C_Find_Active_Page) == 0x000040, "Wrong size on CampaignMapWidget_C_Find_Active_Page");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, Temp_int_Variable) == 0x000000, "Member 'CampaignMapWidget_C_Find_Active_Page::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_Greater_IntInt_ReturnValue) == 0x000008, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, Temp_bool_Variable) == 0x000009, "Member 'CampaignMapWidget_C_Find_Active_Page::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_Not_PreBool_ReturnValue) == 0x00000A, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_GetWidgetAtIndex_ReturnValue) == 0x000010, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_GetWidgetAtIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_GetNumWidgets_ReturnValue) == 0x000018, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_GetNumWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, K2Node_DynamicCast_AsProto_Campaign_Map_Page) == 0x000020, "Member 'CampaignMapWidget_C_Find_Active_Page::K2Node_DynamicCast_AsProto_Campaign_Map_Page' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'CampaignMapWidget_C_Find_Active_Page::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_Subtract_IntInt_ReturnValue) == 0x00002C, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_CheckForMainQuest_TargetQuestFound) == 0x000030, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_CheckForMainQuest_TargetQuestFound' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_CheckForMainQuest_TargetQuestPageIndex) == 0x000034, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_CheckForMainQuest_TargetQuestPageIndex' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000038, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_Find_Active_Page, CallFunc_BooleanAND_ReturnValue) == 0x000039, "Member 'CampaignMapWidget_C_Find_Active_Page::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function CampaignMapWidget.CampaignMapWidget_C.SetTriggerIcon
// 0x06E0 (0x06E0 - 0x0000)
struct CampaignMapWidget_C_SetTriggerIcon final
{
public:
	bool                                          PassThrough;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	ECommonInputType                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            Temp_struct_Variable;                              // 0x0008(0x0090)(ConstParm)
	struct FSlateBrush                            Temp_struct_Variable2;                             // 0x0098(0x0090)(ConstParm)
	struct FSlateBrush                            Temp_struct_Variable3;                             // 0x0128(0x0090)(ConstParm)
	ECommonInputType                              Temp_byte_Variable2;                               // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            Temp_struct_Variable4;                             // 0x01C0(0x0090)(ConstParm)
	struct FSlateBrush                            Temp_struct_Variable5;                             // 0x0250(0x0090)(ConstParm)
	struct FSlateBrush                            Temp_struct_Variable6;                             // 0x02E0(0x0090)(ConstParm)
	class UCommonUIContext*                       CallFunc_GetContext_ReturnValue;                   // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0380(0x0090)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush2;                     // 0x0410(0x0090)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush3;                     // 0x04A0(0x0090)()
	struct FSlateBrush                            K2Node_Select_Default;                             // 0x0530(0x0090)(ConstParm)
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush4;                     // 0x05C0(0x0090)()
	struct FSlateBrush                            K2Node_Select2_Default;                            // 0x0650(0x0090)(ConstParm)
};
static_assert(alignof(CampaignMapWidget_C_SetTriggerIcon) == 0x000008, "Wrong alignment on CampaignMapWidget_C_SetTriggerIcon");
static_assert(sizeof(CampaignMapWidget_C_SetTriggerIcon) == 0x0006E0, "Wrong size on CampaignMapWidget_C_SetTriggerIcon");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, PassThrough) == 0x000000, "Member 'CampaignMapWidget_C_SetTriggerIcon::PassThrough' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_byte_Variable) == 0x000001, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable) == 0x000008, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable2) == 0x000098, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable3) == 0x000128, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable3' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_byte_Variable2) == 0x0001B8, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable4) == 0x0001C0, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable4' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable5) == 0x000250, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable5' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, Temp_struct_Variable6) == 0x0002E0, "Member 'CampaignMapWidget_C_SetTriggerIcon::Temp_struct_Variable6' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, CallFunc_GetContext_ReturnValue) == 0x000370, "Member 'CampaignMapWidget_C_SetTriggerIcon::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, CallFunc_GetCurrentInputType_ReturnValue) == 0x000378, "Member 'CampaignMapWidget_C_SetTriggerIcon::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_MakeStruct_SlateBrush) == 0x000380, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_MakeStruct_SlateBrush2) == 0x000410, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_MakeStruct_SlateBrush2' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_MakeStruct_SlateBrush3) == 0x0004A0, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_MakeStruct_SlateBrush3' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_Select_Default) == 0x000530, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_MakeStruct_SlateBrush4) == 0x0005C0, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_MakeStruct_SlateBrush4' has a wrong offset!");
static_assert(offsetof(CampaignMapWidget_C_SetTriggerIcon, K2Node_Select2_Default) == 0x000650, "Member 'CampaignMapWidget_C_SetTriggerIcon::K2Node_Select2_Default' has a wrong offset!");

}

