#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapPage_Plankerton_13

#include "Basic.hpp"

#include "CampaignMapPage_Plankerton_13_classes.hpp"
#include "CampaignMapPage_Plankerton_13_parameters.hpp"


namespace SDK
{

// Function CampaignMapPage_Plankerton_13.CampaignMapPage_Plankerton_13_C.ExecuteUbergraph_CampaignMapPage_Plankerton_13
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCampaignMapPage_Plankerton_13_C::ExecuteUbergraph_CampaignMapPage_Plankerton_13(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CampaignMapPage_Plankerton_13_C", "ExecuteUbergraph_CampaignMapPage_Plankerton_13");

	Params::CampaignMapPage_Plankerton_13_C_ExecuteUbergraph_CampaignMapPage_Plankerton_13 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CampaignMapPage_Plankerton_13.CampaignMapPage_Plankerton_13_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCampaignMapPage_Plankerton_13_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CampaignMapPage_Plankerton_13_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

