#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapPage_Stonewood_04

#include "Basic.hpp"


namespace SDK::Params
{

// Function CampaignMapPage_Stonewood_04.CampaignMapPage_Stonewood_04_C.ExecuteUbergraph_CampaignMapPage_Stonewood_04
// 0x0004 (0x0004 - 0x0000)
struct CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04) == 0x000004, "Wrong alignment on CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04");
static_assert(sizeof(CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04) == 0x000004, "Wrong size on CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04");
static_assert(offsetof(CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04, EntryPoint) == 0x000000, "Member 'CampaignMapPage_Stonewood_04_C_ExecuteUbergraph_CampaignMapPage_Stonewood_04::EntryPoint' has a wrong offset!");

}

