#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CampaignMapPage_Plankerton_12

#include "Basic.hpp"

#include "CampaignMapPage_Plankerton_12_classes.hpp"
#include "CampaignMapPage_Plankerton_12_parameters.hpp"


namespace SDK
{

// Function CampaignMapPage_Plankerton_12.CampaignMapPage_Plankerton_12_C.ExecuteUbergraph_CampaignMapPage_Plankerton_12
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCampaignMapPage_Plankerton_12_C::ExecuteUbergraph_CampaignMapPage_Plankerton_12(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CampaignMapPage_Plankerton_12_C", "ExecuteUbergraph_CampaignMapPage_Plankerton_12");

	Params::CampaignMapPage_Plankerton_12_C_ExecuteUbergraph_CampaignMapPage_Plankerton_12 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CampaignMapPage_Plankerton_12.CampaignMapPage_Plankerton_12_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCampaignMapPage_Plankerton_12_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CampaignMapPage_Plankerton_12_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

