#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Frontend_Lobby_Halloween

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Frontend_Lobby_Halloween.Frontend_Lobby_Halloween_C
// 0x0000 (0x03A0 - 0x03A0)
class AFrontend_Lobby_Halloween_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Frontend_Lobby_Halloween_C">();
	}
	static class AFrontend_Lobby_Halloween_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontend_Lobby_Halloween_C>();
	}
};
static_assert(alignof(AFrontend_Lobby_Halloween_C) == 0x000008, "Wrong alignment on AFrontend_Lobby_Halloween_C");
static_assert(sizeof(AFrontend_Lobby_Halloween_C) == 0x0003A0, "Wrong size on AFrontend_Lobby_Halloween_C");

}

