#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ninja_ShadowStance

#include "Basic.hpp"

#include "GA_Ninja_ShadowStance_classes.hpp"
#include "GA_Ninja_ShadowStance_parameters.hpp"


namespace SDK
{

// Function GA_Ninja_ShadowStance.GA_Ninja_ShadowStance_C.ExecuteUbergraph_GA_Ninja_ShadowStance
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Ninja_ShadowStance_C::ExecuteUbergraph_GA_Ninja_ShadowStance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_ShadowStance_C", "ExecuteUbergraph_GA_Ninja_ShadowStance");

	Params::GA_Ninja_ShadowStance_C_ExecuteUbergraph_GA_Ninja_ShadowStance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Ninja_ShadowStance.GA_Ninja_ShadowStance_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               EventData                                              (ConstParm, Parm, OutParm, ReferenceParm)

void UGA_Ninja_ShadowStance_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_ShadowStance_C", "K2_ActivateAbilityFromEvent");

	Params::GA_Ninja_ShadowStance_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Ninja_ShadowStance.GA_Ninja_ShadowStance_C.SetupAbility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilitySystemComponent*          Ability_System                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Ninja_ShadowStance_C::SetupAbility(class UAbilitySystemComponent* Ability_System)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_ShadowStance_C", "SetupAbility");

	Params::GA_Ninja_ShadowStance_C_SetupAbility Parms{};

	Parms.Ability_System = Ability_System;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Ninja_ShadowStance.GA_Ninja_ShadowStance_C.K2_ShouldAbilityRespondToEvent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (Parm, ContainsInstancedReference)
// struct FGameplayEventData               Payload                                                (Parm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_Ninja_ShadowStance_C::K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_ShadowStance_C", "K2_ShouldAbilityRespondToEvent");

	Params::GA_Ninja_ShadowStance_C_K2_ShouldAbilityRespondToEvent Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

