#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ninja_Assassination

#include "Basic.hpp"

#include "GA_Ninja_Assassination_classes.hpp"
#include "GA_Ninja_Assassination_parameters.hpp"


namespace SDK
{

// Function GA_Ninja_Assassination.GA_Ninja_Assassination_C.ExecuteUbergraph_GA_Ninja_Assassination
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Ninja_Assassination_C::ExecuteUbergraph_GA_Ninja_Assassination(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_Assassination_C", "ExecuteUbergraph_GA_Ninja_Assassination");

	Params::GA_Ninja_Assassination_C_ExecuteUbergraph_GA_Ninja_Assassination Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Ninja_Assassination.GA_Ninja_Assassination_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               EventData                                              (ConstParm, Parm, OutParm, ReferenceParm)

void UGA_Ninja_Assassination_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_Assassination_C", "K2_ActivateAbilityFromEvent");

	Params::GA_Ninja_Assassination_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Ninja_Assassination.GA_Ninja_Assassination_C.K2_ShouldAbilityRespondToEvent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (Parm, ContainsInstancedReference)
// struct FGameplayEventData               Payload                                                (Parm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_Ninja_Assassination_C::K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_Assassination_C", "K2_ShouldAbilityRespondToEvent");

	Params::GA_Ninja_Assassination_C_K2_ShouldAbilityRespondToEvent Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_Ninja_Assassination.GA_Ninja_Assassination_C.ApplyStack
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_Ninja_Assassination_C::ApplyStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_Assassination_C", "ApplyStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Ninja_Assassination.GA_Ninja_Assassination_C.SetupAbility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilitySystemComponent*          AbilitySystem                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Ninja_Assassination_C::SetupAbility(class UAbilitySystemComponent* AbilitySystem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Ninja_Assassination_C", "SetupAbility");

	Params::GA_Ninja_Assassination_C_SetupAbility Parms{};

	Parms.AbilitySystem = AbilitySystem;

	UObject::ProcessEvent(Func, &Parms);
}

}

