#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HalloweenMapPage_05

#include "Basic.hpp"


namespace SDK::Params
{

// Function HalloweenMapPage_05.HalloweenMapPage_05_C.ExecuteUbergraph_HalloweenMapPage_05
// 0x0004 (0x0004 - 0x0000)
struct HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05) == 0x000004, "Wrong alignment on HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05");
static_assert(sizeof(HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05) == 0x000004, "Wrong size on HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05");
static_assert(offsetof(HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05, EntryPoint) == 0x000000, "Member 'HalloweenMapPage_05_C_ExecuteUbergraph_HalloweenMapPage_05::EntryPoint' has a wrong offset!");

}

