#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Halloween_QuestMapWidget

#include "Basic.hpp"

#include "Halloween_QuestMapWidget_classes.hpp"
#include "Halloween_QuestMapWidget_parameters.hpp"


namespace SDK
{

// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.ExecuteUbergraph_Halloween_QuestMapWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHalloween_QuestMapWidget_C::ExecuteUbergraph_Halloween_QuestMapWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "ExecuteUbergraph_Halloween_QuestMapWidget");

	Params::Halloween_QuestMapWidget_C_ExecuteUbergraph_Halloween_QuestMapWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHalloween_QuestMapWidget_C::BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature");

	Params::Halloween_QuestMapWidget_C_BndEvt__CMButtonPrevious_K2Node_ComponentBoundEvent_414_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHalloween_QuestMapWidget_C::BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature");

	Params::Halloween_QuestMapWidget_C_BndEvt__CMButtonNext_K2Node_ComponentBoundEvent_199_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.Handle OnQuestsUpdated
// (BlueprintCallable, BlueprintEvent)

void UHalloween_QuestMapWidget_C::Handle_OnQuestsUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "Handle OnQuestsUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UHalloween_QuestMapWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHalloween_QuestMapWidget_C::BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature");

	Params::Halloween_QuestMapWidget_C_BndEvt__BtnTest_K2Node_ComponentBoundEvent_514_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UHalloween_QuestMapWidget_C::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "Update");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.Find Active Page
// (Public, BlueprintCallable, BlueprintEvent)

void UHalloween_QuestMapWidget_C::Find_Active_Page()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "Find Active Page");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.SetTriggerIcon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PassThrough                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHalloween_QuestMapWidget_C::SetTriggerIcon(bool PassThrough)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "SetTriggerIcon");

	Params::Halloween_QuestMapWidget_C_SetTriggerIcon Parms{};

	Parms.PassThrough = PassThrough;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Halloween_QuestMapWidget.Halloween_QuestMapWidget_C.Find Current Page - Halloween Event
// (Public, BlueprintCallable, BlueprintEvent)

void UHalloween_QuestMapWidget_C::Find_Current_Page_Minus_Halloween_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Halloween_QuestMapWidget_C", "Find Current Page - Halloween Event");

	UObject::ProcessEvent(Func, nullptr);
}

}

