#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemInspectionItemExtraDetailsHostPanel

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemInspectionItemExtraDetailsHostPanel.ItemInspectionItemExtraDetailsHostPanel_C
// 0x0000 (0x02A0 - 0x02A0)
class UItemInspectionItemExtraDetailsHostPanel_C final : public UFortItemDetailsHostPanel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemInspectionItemExtraDetailsHostPanel_C">();
	}
	static class UItemInspectionItemExtraDetailsHostPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemInspectionItemExtraDetailsHostPanel_C>();
	}
};
static_assert(alignof(UItemInspectionItemExtraDetailsHostPanel_C) == 0x000008, "Wrong alignment on UItemInspectionItemExtraDetailsHostPanel_C");
static_assert(sizeof(UItemInspectionItemExtraDetailsHostPanel_C) == 0x0002A0, "Wrong size on UItemInspectionItemExtraDetailsHostPanel_C");

}

