#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PartyDisplayManagerBP

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.ExecuteUbergraph_PartyDisplayManagerBP
// 0x03E0 (0x03E0 - 0x0000)
struct PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<TSoftObjectPtr<class UObject>>         CallFunc_GetPreviewAssets_Assets;                  // 0x0010(0x0010)(ZeroConstructor, ReferenceParm)
	class UFortItem*                              K2Node_Event_ItemToView;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetWeaponPlacementTransform_ReturnValue;  // 0x0030(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0060(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x006C(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0078(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0088(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult2;      // 0x0110(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0198(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x01A8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue2;           // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0231(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_232[0x6];                                      // 0x0232(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    K2Node_Event_ItemWhoseAssetsWereLoaded;            // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UObject*>                        K2Node_Event_LoadedAssets;                         // 0x0240(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition2;  // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition3;  // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0261(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0262(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_263[0x5];                                      // 0x0263(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition4;  // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UStaticMesh>             CallFunc_GetPreviewStaticMeshAsset_Asset;          // 0x0270(0x0020)(HasGetValueTypeHash)
	bool                                          CallFunc_GetPreviewStaticMeshAsset_ReturnValue;    // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x3];                                      // 0x0291(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Conv_FloatToVector_ReturnValue;           // 0x0294(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_Conv_AssetToObject_ReturnValue;           // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USkeletalMesh>           CallFunc_GetPreviewSkeletalMeshAsset_Asset;        // 0x02A8(0x0020)(HasGetValueTypeHash)
	bool                                          CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue;  // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_DynamicCast_AsStatic_Mesh;                  // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_AssetToObject_ReturnValue2;          // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition5;  // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          K2Node_DynamicCast_AsSkeletal_Mesh;                // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F9[0x7];                                      // 0x02F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UStaticMesh>             CallFunc_GetPreviewStaticMeshAsset_Asset2;         // 0x0300(0x0020)(HasGetValueTypeHash)
	bool                                          CallFunc_GetPreviewStaticMeshAsset_ReturnValue2;   // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_AssetToObject_ReturnValue3;          // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USkeletalMesh>           CallFunc_GetPreviewSkeletalMeshAsset_Asset2;       // 0x0330(0x0020)(HasGetValueTypeHash)
	bool                                          CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue2; // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x7];                                      // 0x0351(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_DynamicCast_AsStatic_Mesh2;                 // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess3;                      // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x7];                                      // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_AssetToObject_ReturnValue4;          // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          K2Node_DynamicCast_AsSkeletal_Mesh2;               // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess4;                      // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortRarity                                   CallFunc_GetRarity_ReturnValue;                    // 0x0379(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_37A[0x6];                                      // 0x037A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetLargePreviewImage_ReturnValue;         // 0x0380(0x0020)(HasGetValueTypeHash)
	class UObject*                                CallFunc_Conv_AssetToObject_ReturnValue5;          // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetSchematicCraftingResultBP_ReturnValue; // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess5;                      // 0x03B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x03B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BA[0x2];                                      // 0x03BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Conv_FloatToVector_ReturnValue2;          // 0x03BC(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition6;  // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x03D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP");
static_assert(sizeof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP) == 0x0003E0, "Wrong size on PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, EntryPoint) == 0x000000, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition) == 0x000008, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewAssets_Assets) == 0x000010, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewAssets_Assets' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_Event_ItemToView) == 0x000020, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_Event_ItemToView' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_IsDedicatedServer_ReturnValue) == 0x000028, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetWeaponPlacementTransform_ReturnValue) == 0x000030, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetWeaponPlacementTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_BreakTransform_Location) == 0x000060, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_BreakTransform_Rotation) == 0x00006C, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_BreakTransform_Scale) == 0x000078, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000088, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_K2_SetWorldLocation_SweepHitResult2) == 0x000110, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_K2_SetWorldLocation_SweepHitResult2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000198, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x0001A8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_IsDedicatedServer_ReturnValue2) == 0x000230, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_IsDedicatedServer_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_IsValid_ReturnValue) == 0x000231, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_Event_ItemWhoseAssetsWereLoaded) == 0x000238, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_Event_ItemWhoseAssetsWereLoaded' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_Event_LoadedAssets) == 0x000240, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_Event_LoadedAssets' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition2) == 0x000250, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition3) == 0x000258, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_IsValid_ReturnValue2) == 0x000260, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000261, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Not_PreBool_ReturnValue) == 0x000262, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition4) == 0x000268, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition4' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewStaticMeshAsset_Asset) == 0x000270, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewStaticMeshAsset_Asset' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewStaticMeshAsset_ReturnValue) == 0x000290, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewStaticMeshAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_FloatToVector_ReturnValue) == 0x000294, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_FloatToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_AssetToObject_ReturnValue) == 0x0002A0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_AssetToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewSkeletalMeshAsset_Asset) == 0x0002A8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewSkeletalMeshAsset_Asset' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue) == 0x0002C8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_AsStatic_Mesh) == 0x0002D0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_AsStatic_Mesh' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_bSuccess) == 0x0002D8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_AssetToObject_ReturnValue2) == 0x0002E0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_AssetToObject_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition5) == 0x0002E8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition5' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_AsSkeletal_Mesh) == 0x0002F0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_AsSkeletal_Mesh' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_bSuccess2) == 0x0002F8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewStaticMeshAsset_Asset2) == 0x000300, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewStaticMeshAsset_Asset2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewStaticMeshAsset_ReturnValue2) == 0x000320, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewStaticMeshAsset_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_AssetToObject_ReturnValue3) == 0x000328, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_AssetToObject_ReturnValue3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewSkeletalMeshAsset_Asset2) == 0x000330, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewSkeletalMeshAsset_Asset2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue2) == 0x000350, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetPreviewSkeletalMeshAsset_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_AsStatic_Mesh2) == 0x000358, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_AsStatic_Mesh2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_bSuccess3) == 0x000360, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_bSuccess3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_AssetToObject_ReturnValue4) == 0x000368, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_AssetToObject_ReturnValue4' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_AsSkeletal_Mesh2) == 0x000370, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_AsSkeletal_Mesh2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_bSuccess4) == 0x000378, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_bSuccess4' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetRarity_ReturnValue) == 0x000379, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetRarity_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetLargePreviewImage_ReturnValue) == 0x000380, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetLargePreviewImage_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_AssetToObject_ReturnValue5) == 0x0003A0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_AssetToObject_ReturnValue5' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetSchematicCraftingResultBP_ReturnValue) == 0x0003A8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetSchematicCraftingResultBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_AsTexture_2D) == 0x0003B0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_DynamicCast_bSuccess5) == 0x0003B8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_DynamicCast_bSuccess5' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_IsValid_ReturnValue3) == 0x0003B9, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_IsValid_ReturnValue3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_Conv_FloatToVector_ReturnValue2) == 0x0003BC, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_Conv_FloatToVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, CallFunc_GetItemDefinitionToShow_ItemDefinition6) == 0x0003C8, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::CallFunc_GetItemDefinitionToShow_ItemDefinition6' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP, K2Node_Event_DeltaSeconds) == 0x0003D0, "Member 'PartyDisplayManagerBP_C_ExecuteUbergraph_PartyDisplayManagerBP::K2Node_Event_DeltaSeconds' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct PartyDisplayManagerBP_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PartyDisplayManagerBP_C_ReceiveTick) == 0x000004, "Wrong alignment on PartyDisplayManagerBP_C_ReceiveTick");
static_assert(sizeof(PartyDisplayManagerBP_C_ReceiveTick) == 0x000004, "Wrong size on PartyDisplayManagerBP_C_ReceiveTick");
static_assert(offsetof(PartyDisplayManagerBP_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'PartyDisplayManagerBP_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.HandleLoadingAssetsForItemCompleted
// 0x0018 (0x0018 - 0x0000)
struct PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted final
{
public:
	class UFortItemDefinition*                    ItemWhoseAssetsWereLoaded;                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UObject*>                        LoadedAssets;                                      // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted) == 0x000008, "Wrong alignment on PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted");
static_assert(sizeof(PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted) == 0x000018, "Wrong size on PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted");
static_assert(offsetof(PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted, ItemWhoseAssetsWereLoaded) == 0x000000, "Member 'PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted::ItemWhoseAssetsWereLoaded' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted, LoadedAssets) == 0x000008, "Member 'PartyDisplayManagerBP_C_HandleLoadingAssetsForItemCompleted::LoadedAssets' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.ShowItem
// 0x0008 (0x0008 - 0x0000)
struct PartyDisplayManagerBP_C_ShowItem final
{
public:
	class UFortItem*                              ItemToView;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PartyDisplayManagerBP_C_ShowItem) == 0x000008, "Wrong alignment on PartyDisplayManagerBP_C_ShowItem");
static_assert(sizeof(PartyDisplayManagerBP_C_ShowItem) == 0x000008, "Wrong size on PartyDisplayManagerBP_C_ShowItem");
static_assert(offsetof(PartyDisplayManagerBP_C_ShowItem, ItemToView) == 0x000000, "Member 'PartyDisplayManagerBP_C_ShowItem::ItemToView' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.ResetVisuals
// 0x0001 (0x0001 - 0x0000)
struct PartyDisplayManagerBP_C_ResetVisuals final
{
public:
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_ResetVisuals) == 0x000001, "Wrong alignment on PartyDisplayManagerBP_C_ResetVisuals");
static_assert(sizeof(PartyDisplayManagerBP_C_ResetVisuals) == 0x000001, "Wrong size on PartyDisplayManagerBP_C_ResetVisuals");
static_assert(offsetof(PartyDisplayManagerBP_C_ResetVisuals, CallFunc_SetStaticMesh_ReturnValue) == 0x000000, "Member 'PartyDisplayManagerBP_C_ResetVisuals::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.SetupSkeletalMeshVisuals
// 0x00D0 (0x00D0 - 0x0000)
struct PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals final
{
public:
	class USkeletalMesh*                          NewMesh;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0010(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x0040(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals");
static_assert(sizeof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals) == 0x0000D0, "Wrong size on PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals, NewMesh) == 0x000000, "Member 'PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals::NewMesh' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals, CallFunc_GetItemDefinitionToShow_ItemDefinition) == 0x000008, "Member 'PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals::CallFunc_GetItemDefinitionToShow_ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals, CallFunc_GetTransform_ReturnValue) == 0x000010, "Member 'PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x000040, "Member 'PartyDisplayManagerBP_C_SetupSkeletalMeshVisuals::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.SetupStaticMeshVisuals
// 0x00D0 (0x00D0 - 0x0000)
struct PartyDisplayManagerBP_C_SetupStaticMeshVisuals final
{
public:
	class UStaticMesh*                            NewMesh;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0010(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x0040(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_SetupStaticMeshVisuals");
static_assert(sizeof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals) == 0x0000D0, "Wrong size on PartyDisplayManagerBP_C_SetupStaticMeshVisuals");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals, NewMesh) == 0x000000, "Member 'PartyDisplayManagerBP_C_SetupStaticMeshVisuals::NewMesh' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals, CallFunc_GetItemDefinitionToShow_ItemDefinition) == 0x000008, "Member 'PartyDisplayManagerBP_C_SetupStaticMeshVisuals::CallFunc_GetItemDefinitionToShow_ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals, CallFunc_GetTransform_ReturnValue) == 0x000010, "Member 'PartyDisplayManagerBP_C_SetupStaticMeshVisuals::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x000040, "Member 'PartyDisplayManagerBP_C_SetupStaticMeshVisuals::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetupStaticMeshVisuals, CallFunc_SetStaticMesh_ReturnValue) == 0x0000C8, "Member 'PartyDisplayManagerBP_C_SetupStaticMeshVisuals::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.GetPreviewMeshWorldTransform
// 0x0150 (0x0150 - 0x0000)
struct PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform final
{
public:
	struct FTransform                             ReturnValue;                                       // 0x0000(0x0030)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable;                               // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionToShow_ItemDefinition;   // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0xF];                                       // 0x0041(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetItemPreviewOffset_ReturnValue;         // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_GetWeaponPlacementTransform_ReturnValue;  // 0x0080(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	float                                         K2Node_Select_Default;                             // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x00B4(0x000C)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00C0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue;            // 0x00F0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue2;           // 0x0120(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform");
static_assert(sizeof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform) == 0x000150, "Wrong size on PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, ReturnValue) == 0x000000, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, Temp_float_Variable) == 0x000030, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, Temp_bool_Variable) == 0x000034, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_GetItemDefinitionToShow_ItemDefinition) == 0x000038, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_GetItemDefinitionToShow_ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_GetItemPreviewOffset_ReturnValue) == 0x000050, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_GetItemPreviewOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_GetWeaponPlacementTransform_ReturnValue) == 0x000080, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_GetWeaponPlacementTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, K2Node_Select_Default) == 0x0000B0, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_MakeRotator_ReturnValue) == 0x0000B4, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_MakeTransform_ReturnValue) == 0x0000C0, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_ComposeTransforms_ReturnValue) == 0x0000F0, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_ComposeTransforms_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform, CallFunc_ComposeTransforms_ReturnValue2) == 0x000120, "Member 'PartyDisplayManagerBP_C_GetPreviewMeshWorldTransform::CallFunc_ComposeTransforms_ReturnValue2' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.GetItemPreviewOffset
// 0x01D0 (0x01D0 - 0x0000)
struct PartyDisplayManagerBP_C_GetItemPreviewOffset final
{
public:
	class UFortItemDefinition*                    ItemDefinition;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             ReturnValue;                                       // 0x0010(0x0030)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0xF];                                       // 0x0041(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetPreviewMeshOffset_ReturnValue;         // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0080(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x00B0(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x00BC(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x00C8(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_VectorVector_ReturnValue;      // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_VectorVector_ReturnValue2;     // 0x00D5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_RotatorRotator_ReturnValue;    // 0x00D6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00D7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue2;                  // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             K2Node_Select_Default;                             // 0x00E0(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location2;                 // 0x0110(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation2;                 // 0x011C(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale2;                    // 0x0128(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0xC];                                      // 0x0134(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue2;               // 0x0140(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue3;               // 0x0170(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue;            // 0x01A0(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_GetItemPreviewOffset) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_GetItemPreviewOffset");
static_assert(sizeof(PartyDisplayManagerBP_C_GetItemPreviewOffset) == 0x0001D0, "Wrong size on PartyDisplayManagerBP_C_GetItemPreviewOffset");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, ItemDefinition) == 0x000000, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, ReturnValue) == 0x000010, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, Temp_bool_Variable) == 0x000040, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_GetPreviewMeshOffset_ReturnValue) == 0x000050, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_GetPreviewMeshOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_MakeTransform_ReturnValue) == 0x000080, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Location) == 0x0000B0, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Rotation) == 0x0000BC, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Scale) == 0x0000C8, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_EqualEqual_VectorVector_ReturnValue) == 0x0000D4, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_EqualEqual_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_EqualEqual_VectorVector_ReturnValue2) == 0x0000D5, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_EqualEqual_VectorVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_EqualEqual_RotatorRotator_ReturnValue) == 0x0000D6, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_EqualEqual_RotatorRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BooleanAND_ReturnValue) == 0x0000D7, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BooleanAND_ReturnValue2) == 0x0000D8, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BooleanAND_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, K2Node_Select_Default) == 0x0000E0, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Location2) == 0x000110, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Location2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Rotation2) == 0x00011C, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Rotation2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_BreakTransform_Scale2) == 0x000128, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_BreakTransform_Scale2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_MakeTransform_ReturnValue2) == 0x000140, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_MakeTransform_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_MakeTransform_ReturnValue3) == 0x000170, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_MakeTransform_ReturnValue3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemPreviewOffset, CallFunc_ComposeTransforms_ReturnValue) == 0x0001A0, "Member 'PartyDisplayManagerBP_C_GetItemPreviewOffset::CallFunc_ComposeTransforms_ReturnValue' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.UpdatePreviewMeshTransforms
// 0x00C0 (0x00C0 - 0x0000)
struct PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms final
{
public:
	struct FTransform                             CallFunc_GetPreviewMeshWorldTransform_ReturnValue; // 0x0000(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x0030(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Percent_FloatFloat_ReturnValue;           // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms");
static_assert(sizeof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms) == 0x0000C0, "Wrong size on PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms");
static_assert(offsetof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms, CallFunc_GetPreviewMeshWorldTransform_ReturnValue) == 0x000000, "Member 'PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms::CallFunc_GetPreviewMeshWorldTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x000030, "Member 'PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000B8, "Member 'PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms, CallFunc_Percent_FloatFloat_ReturnValue) == 0x0000BC, "Member 'PartyDisplayManagerBP_C_UpdatePreviewMeshTransforms::CallFunc_Percent_FloatFloat_ReturnValue' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.GetWeaponPlacementTransform
// 0x0100 (0x0100 - 0x0000)
struct PartyDisplayManagerBP_C_GetWeaponPlacementTransform final
{
public:
	struct FTransform                             ReturnValue;                                       // 0x0000(0x0030)(ConstParm, Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0030(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0060(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0xF];                                       // 0x0091(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue2;                // 0x00A0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue;            // 0x00D0(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform) == 0x000010, "Wrong alignment on PartyDisplayManagerBP_C_GetWeaponPlacementTransform");
static_assert(sizeof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform) == 0x000100, "Wrong size on PartyDisplayManagerBP_C_GetWeaponPlacementTransform");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, ReturnValue) == 0x000000, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, CallFunc_MakeTransform_ReturnValue) == 0x000030, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, CallFunc_GetTransform_ReturnValue) == 0x000060, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, CallFunc_IsValid_ReturnValue) == 0x000090, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, CallFunc_GetTransform_ReturnValue2) == 0x0000A0, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::CallFunc_GetTransform_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetWeaponPlacementTransform, CallFunc_ComposeTransforms_ReturnValue) == 0x0000D0, "Member 'PartyDisplayManagerBP_C_GetWeaponPlacementTransform::CallFunc_ComposeTransforms_ReturnValue' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.SetUIOverrideVisuals
// 0x00D0 (0x00D0 - 0x0000)
struct PartyDisplayManagerBP_C_SetUIOverrideVisuals final
{
public:
	class UTexture2D*                             Large_Texture;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    Item;                                              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   Rarity;                                            // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortRarityItemData                    CallFunc_BPGetRarityData_ReturnValue;              // 0x0018(0x0080)()
	class FString                                 CallFunc_GetPersistentName_ReturnValue;            // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_FindSubstring_ReturnValue;                // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_IntToBool_ReturnValue;               // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_FindSubstring_ReturnValue2;               // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FindSubstring_ReturnValue3;               // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_IntToBool_ReturnValue2;              // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Conv_IntToBool_ReturnValue3;              // 0x00C5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C6[0x2];                                       // 0x00C6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_FindSubstring_ReturnValue4;               // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_IntToBool_ReturnValue4;              // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_SetUIOverrideVisuals) == 0x000008, "Wrong alignment on PartyDisplayManagerBP_C_SetUIOverrideVisuals");
static_assert(sizeof(PartyDisplayManagerBP_C_SetUIOverrideVisuals) == 0x0000D0, "Wrong size on PartyDisplayManagerBP_C_SetUIOverrideVisuals");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, Large_Texture) == 0x000000, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::Large_Texture' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, Item) == 0x000008, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::Item' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, Rarity) == 0x000010, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::Rarity' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_BPGetRarityData_ReturnValue) == 0x000018, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_BPGetRarityData_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_GetPersistentName_ReturnValue) == 0x000098, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_GetPersistentName_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_FindSubstring_ReturnValue) == 0x0000A8, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_FindSubstring_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x0000B0, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_Conv_IntToBool_ReturnValue) == 0x0000B8, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_Conv_IntToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_FindSubstring_ReturnValue2) == 0x0000BC, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_FindSubstring_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_FindSubstring_ReturnValue3) == 0x0000C0, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_FindSubstring_ReturnValue3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_Conv_IntToBool_ReturnValue2) == 0x0000C4, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_Conv_IntToBool_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_Conv_IntToBool_ReturnValue3) == 0x0000C5, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_Conv_IntToBool_ReturnValue3' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_FindSubstring_ReturnValue4) == 0x0000C8, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_FindSubstring_ReturnValue4' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_SetUIOverrideVisuals, CallFunc_Conv_IntToBool_ReturnValue4) == 0x0000CC, "Member 'PartyDisplayManagerBP_C_SetUIOverrideVisuals::CallFunc_Conv_IntToBool_ReturnValue4' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.GetItemDefinitionToShow
// 0x0028 (0x0028 - 0x0000)
struct PartyDisplayManagerBP_C_GetItemDefinitionToShow final
{
public:
	class UFortItemDefinition*                    ItemDefinition;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    CallFunc_GetSchematicCraftingResultBP_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B[0x5];                                       // 0x001B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    K2Node_Select_Default;                             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PartyDisplayManagerBP_C_GetItemDefinitionToShow) == 0x000008, "Wrong alignment on PartyDisplayManagerBP_C_GetItemDefinitionToShow");
static_assert(sizeof(PartyDisplayManagerBP_C_GetItemDefinitionToShow) == 0x000028, "Wrong size on PartyDisplayManagerBP_C_GetItemDefinitionToShow");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, ItemDefinition) == 0x000000, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::ItemDefinition' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, CallFunc_GetItemDefinitionBP_ReturnValue) == 0x000008, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::CallFunc_GetItemDefinitionBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, CallFunc_GetSchematicCraftingResultBP_ReturnValue) == 0x000010, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::CallFunc_GetSchematicCraftingResultBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, CallFunc_IsValid_ReturnValue2) == 0x000019, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, Temp_bool_Variable) == 0x00001A, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetItemDefinitionToShow, K2Node_Select_Default) == 0x000020, "Member 'PartyDisplayManagerBP_C_GetItemDefinitionToShow::K2Node_Select_Default' has a wrong offset!");

// Function PartyDisplayManagerBP.PartyDisplayManagerBP_C.GetMeshForCurrentDisplayedItem
// 0x0038 (0x0038 - 0x0000)
struct PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem final
{
public:
	class UMeshComponent*                         OutDisplayedMesh;                                  // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICustomCharacterPartOwnerInterface> CallFunc_GetCustomizationRootSkeletalMeshComponent_self_CastInput; // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class USkeletalMeshComponent*                 CallFunc_GetCustomizationRootSkeletalMeshComponent_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem) == 0x000008, "Wrong alignment on PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem");
static_assert(sizeof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem) == 0x000038, "Wrong size on PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, OutDisplayedMesh) == 0x000000, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::OutDisplayedMesh' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue) == 0x000008, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_GetHeroPlayerPawnForCurrentDisplayedItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_GetCustomizationRootSkeletalMeshComponent_self_CastInput) == 0x000018, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_GetCustomizationRootSkeletalMeshComponent_self_CastInput' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_GetCustomizationRootSkeletalMeshComponent_ReturnValue) == 0x000028, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_GetCustomizationRootSkeletalMeshComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_IsValid_ReturnValue2) == 0x000030, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem, CallFunc_IsValid_ReturnValue3) == 0x000031, "Member 'PartyDisplayManagerBP_C_GetMeshForCurrentDisplayedItem::CallFunc_IsValid_ReturnValue3' has a wrong offset!");

}

